version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/my_photo_app 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh 
      timeout: 300
      runas: ec2-user 
  ApplicationStart:
    - location: scripts/start_app.sh 
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ec2-user