version: 0.0
os: linux
files:
  - source: / # Deploy all files from the root of the artifact
    destination: /home/ec2-user/my_photo_app # Or your target deployment directory (ensure this path is correct for your EC2 instance)
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh # CHANGE THIS BACK! Look in 'scripts/' folder
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh           # CHANGE THIS BACK! Look in 'scripts/' folder
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh            # CHANGE THIS BACK! Look in 'scripts/' folder
      timeout: 60
      runas: root