version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/my_photo_app 
hooks:
  BeforeInstall:
    - location: scripts/setup_deployment_dir.sh # <-- NEW SCRIPT
      timeout: 60
      runas: root # Run as root to ensure directory creation/ownership
    - location: scripts/install_dependencies.sh 
      timeout: 300
      runas: ec2-user # This remains ec2-user as your script expects
  ApplicationStart:
    - location: scripts/start_app.sh 
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ec2-user