version: 0.0
os: linux
files:
  - source: / # Deploy all files from the root of the artifact
    destination: /home/ec2-user/my_photo_app # Deploy them to this directory on the EC2 instance
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_app.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: stop_app.sh
      timeout: 60
      runas: root