version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      # Create a virtual environment named .venv
      - python3 -m venv .venv 
      # Activate the virtual environment using the portable '.' command
      - . .venv/bin/activate 
      # Install Python dependencies into the virtual environment
      - pip install -r requirements.txt
      - echo "Python dependencies installed in virtual environment."
      # Deactivate is not needed here as the shell context ends.
      
  build:
    commands:
      - echo "Build phase started..."
      # Grant execute permissions to the scripts located in the 'scripts' subdirectory
      - chmod +x scripts/install_dependencies.sh
      - chmod +x scripts/start_app.sh
      - chmod +x scripts/stop_app.sh
      # Ensure permissions for .venv directories/files within the artifact
      # These commands make sure the files inside .venv are readable and executable
      # by the ec2-user after deployment.
      - find .venv -type f -exec chmod 644 {} + # Make files readable
      - find .venv -type d -exec chmod 755 {} + # Make directories traversable
artifacts:
  files:
    - 'app.py'
    - 'aws_utils.py'
    - 'config.py'
    - 'requirements.txt'
    - 'bashscript.txt'
    - 'appspec.yml'
    - 'scripts/**/*'
    # Include the entire virtual environment directory in the artifact
    - '.venv/**/*' 
  discard-paths: no # Ensure 'scripts/' and '.venv/' paths are preserved in the artifact