version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # No longer installing dependencies or creating venv in CodeBuild
      - echo "Skipping Python dependency installation in CodeBuild. This will happen on EC2."
      
  build:
    commands:
      - echo "Build phase started..."
      # Grant execute permissions to all scripts in the 'scripts' subdirectory
      - chmod +x scripts/install_dependencies.sh
      - chmod +x scripts/start_app.sh
      - chmod +x scripts/stop_app.sh
      - chmod +x scripts/setup_deployment_dir.sh # Keep this one

artifacts:
  files:
    - 'app.py'
    - 'aws_utils.py'
    - 'config.py'
    - 'requirements.txt'
    - 'bashscript.txt'
    - 'appspec.yml'
    - 'scripts/**/*' # This will include all scripts, including the new setup_deployment_dir.sh
    # Removed: - '.venv/**/*' 
  discard-paths: no