version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt --target .
  build:
    commands:
      - echo "Build phase started..."
      # Grant execute permissions to the scripts located in the 'scripts' subdirectory in the build environment
      - chmod +x scripts/install_dependencies.sh
      - chmod +x scripts/start_app.sh
      - chmod +x scripts/stop_app.sh
artifacts:
  files:
    - 'app.py'
    - 'aws_utils.py'
    - 'config.py'
    - 'requirements.txt'
    - 'bashscript.txt'
    - 'appspec.yml'
    # Include the entire scripts directory, preserving its path
    - 'scripts/**/*' # This means all files within the 'scripts' directory will be included with their 'scripts/' prefix in the artifact
  discard-paths: no # Crucial: This ensures the 'scripts/' directory structure is preserved in the artifact