version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11 # Ensure this matches your project's Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt --target . # Install to current directory
  build:
    commands:
      - echo "Build phase started..."
      # No explicit build commands needed if just packaging existing files
artifacts:
  files:
    - 'app.py'
    - 'aws_utils.py'
    - 'config.py'
    - 'requirements.txt'
    - 'bashscript.txt'
    - 'appspec.yml'
    - 'scripts/**/*' # This captures all files within the scripts directory and its subdirectories
  discard-paths: yes # THIS IS CRITICAL. It puts all listed files/folders directly at the root of the ZIP.
  # base-directory: build_output # REMOVE THIS IF IT'S PRESENT IN YOUR ARTIFACTS SECTION