version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt --target .
  build:
    commands:
      - echo "Build phase started..."
      # Add this line to ensure scripts are executable before they are packaged into the artifact
      # Refer to them by their path relative to the root of the cloned repo
      - chmod +x scripts/install_dependencies.sh
      - chmod +x scripts/start_app.sh
      - chmod +x scripts/stop_app.sh
artifacts:
  files:
    - 'app.py'
    - 'aws_utils.py'
    - 'config.py'
    - 'requirements.txt'
    - 'bashscript.txt'
    - 'appspec.yml'
    # List the scripts directly, as they are flattened to the root of the artifact
    - 'install_dependencies.sh'
    - 'start_app.sh'
    - 'stop_app.sh'
  discard-paths: yes